name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6.x'

    - name: Setup venv
      run: python -m venv venv && source venv/bin/activate && pip install -r requirements.txt

    - name: Package
      run: source venv/bin/activate && fbs freeze
