name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-16.04

    steps:
    - name: Install dependencies
      run: sudo apt-get install libusb-1.0-0-dev libudev-dev

    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6.x'

    - name: Setup venv
      run: python -m venv venv && source venv/bin/activate && pip install -r requirements.txt

    - name: Build
      run: source venv/bin/activate && fbs freeze

    - name: Prepare package
      run: mkdir target/out && mv "target/Womier Flasher" "target/out/Womier Flasher"

    - uses: actions/upload-artifact@v1
      with:
        name: flasher-linux
        path: target/out

  build-mac:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6.x'

    - name: Setup venv
      run: python -m venv venv && source venv/bin/activate && pip install -r requirements.txt

    - name: Build
      run: source venv/bin/activate && fbs freeze

    - uses: actions/upload-artifact@v1
      with:
        name: flasher-mac
        path: target
