name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6.x'

    - name: Setup venv
      run: python -m venv venv && source venv/bin/activate && pip install -r requirements.txt

    - name: Build
      run: source venv/bin/activate && fbs freeze

    - name: Prepare package
      run: mkdir target/out && mv "target/Womier Flasher" "target/out/Womier Flasher"

    - uses: actions/upload-artifact@v1
      with:
        name: flasher-linux
        path: target/out
